export { default as Signup } from './Signup'
export { default as Login } from './Login'
export { default as Account } from './Account'
export { default as Landing } from './Landing'
export { default as Home } from './Home'
